# Generated by Django 6.0.3 on 2026-04-21 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0001_initial'),
        ('orders', '0002_cartitem_alter_cart_options_alter_wishlist_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='cartitem',
            name='orders_cart_cart_id_dc9f49_idx',
        ),
        migrations.RemoveIndex(
            model_name='cartitem',
            name='orders_cart_accesso_0b80d7_idx',
        ),
        migrations.RemoveIndex(
            model_name='wishlist',
            name='orders_wish_user_id_748f16_idx',
        ),
        migrations.RemoveIndex(
            model_name='wishlist',
            name='orders_wish_accesso_3a3ce9_idx',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='accessory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessories.accessory'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='accessory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessories.accessory'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='created_at',
        ),
    ]
