# Generated by Django 6.0.3 on 2026-04-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('registration_number', models.CharField(default='TEMP123', max_length=50, unique=True)),
                ('is_available', models.BooleanField(default=True)),
                ('fuel_type', models.CharField(default='Petrol', max_length=50)),
                ('transmission', models.CharField(default='Manual', max_length=50)),
                ('seats', models.IntegerField(default=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
            ],
        ),
    ]
