# Generated by Django 6.0.3 on 2026-04-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_car_fuel_type_alter_car_transmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_type',
            field=models.CharField(choices=[('rental', 'Rental'), ('sale', 'Sale')], default='rental', max_length=10),
        ),
    ]
