# Generated by Django 6.0.3 on 2026-04-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_car_options_alter_car_car_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
