# Generated by Django 6.0.3 on 2026-04-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_rename_location_car_address_alter_car_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carimage',
            name='image',
            field=models.URLField(),
        ),
    ]
