# Generated by Django 6.0.3 on 2026-04-20 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_alter_carimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='address',
            new_name='location',
        ),
    ]
