# Generated by Django 6.0.3 on 2026-04-25 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
