# Generated by Django 6.0.3 on 2026-04-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0006_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='actual_return_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='fine_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='return_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
