# Generated by Django 6.0.3 on 2026-04-23 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_userchat_usermessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermessage',
            name='sender',
        ),
        migrations.AddField(
            model_name='usermessage',
            name='sender_name',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='usermessage',
            name='status',
            field=models.CharField(default='sent', max_length=20),
        ),
    ]
